artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/abhay560/Data-Engineering-Internship-Bosch/raw/refs/heads/main/AirQuality.csv"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/AirQualityUCI.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  failed_data_dir: artifacts/quarantine
  valid_data_dir: artifacts/valid_data

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/valid_data/valid_data.csv